export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const LOGOUT_USER = "LOGOUT_USER";
